--HTC_SPAWN_CONFIGS = {
--    "AmbulanceDriver",
--    "ArmyCamoDesert",
--    "ArmyCamoGreen",
--    "ArmyServiceUniform",
--    "BaseballFan_KY",
--    "BaseballFan_Rangers",
--    "BaseballFan_Z",
--    "BaseballPlayer_KY",
--    "BaseballPlayer_Rangers",
--    "BaseballPlayer_Z",
--    "Bathrobe",
--    "Bedroom",
--    "Biker",
--    "Bowling",
--    "BoxingBlue",
--    "BoxingRed",
--    "Camper",
--    "Chef",
--    "Classy",
--    "Cook_Generic",
--    "Cook_IceCream",
--    "Cook_Spiffos",
--    "Cyclist",
--    "Doctor",
--    "DressLong",
--    "DressNormal",
--    "DressShort",
--    "Farmer",
--    "Fireman",
--    "FiremanFullSuit",
--    "FitnessInstructor",
--    "Fossoil",
--    "Gas2Go",
--    "Generic_Skirt",
--    "Generic01",
--    "Generic02",
--    "Generic03",
--    "Generic04",
--    "Generic05",
--    "GigaMart_Employee",
--    "Golfer",
--    "HazardSuit",
--    "Hobbo",
--    "HospitalPatient",
--    "Jackie_Jaye",
--    "Joan",
--    "Jockey04",
--    "Jockey05",
--    "Kate",
--    "Kirsty_Kormick",
--    "Mannequin1",
--    "Mannequin2",
--    "Nurse",
--    "OfficeWorkerSkirt",
--    "Party",
--    "Pharmacist",
--    "Police",
--    "PoliceState",
--    "Postal",
--    "PrivateMilitia",
--    "Punk",
--    "Ranger",
--    "Redneck",
--    "Rocker",
--    "Santa",
--    "SantaGreen",
--    "ShellSuit_Black",
--    "ShellSuit_Blue",
--    "ShellSuit_Green",
--    "ShellSuit_Pink",
--    "ShellSuit_Teal",
--    "Ski Spiffo",
--    "SportsFan",
--    "StreetSports",
--    "StripperBlack",
--    "StripperPink",
--    "Student",
--    "Survivalist",
--    "Survivalist02",
--    "Survivalist03",
--    "Swimmer",
--    "Teacher",
--    "ThunderGas",
--    "TinFoilHat",
--    "Tourist",
--    "Trader",
--    "TutorialMom",
--    "Varsity",
--    "Young",
--    "Bob",
--    "ConstructionWorker",
--    "Dean",
--    "Duke",
--    "Fisherman",
--    "Frank_Hemingway",
--    "Ghillie",
--    "Groom",
--    "Jewelry",
--    "John",
--    "Judge_Matt_Hass",
--    "MallSecurity",
--    "Mayor_West_point",
--    "McCoys",
--    "Mechanic",
--    "MetalWorker",
--    "OfficeWorker",
--    "PokerDealer",
--    "Priest",
--    "PrisonGuard",
--    "Rev_Peter_Watts",
--    "Raider",
--    "Sir_Twiggy",
--    "TutorialDad",
--    "Veteran",

HTC_SPAWN_CONFIGS = {
    DeepForest = {
        "HockeyPsycho",
        "Hunter",
        "Woodcut",
        "AirCrew",
        "ArmyCamoGreen",
        "ArmyServiceUniform",
        "Veteran" },
    TownZone = {
        "Mechanic",
        "PoliceRiot",
        "PrisonGuard",
        "Trader",
        "Waiter_TacoDelPancho",
        "Security",
        "ArmyServiceUniform",
        "Waiter_Classy",
        "Waiter_Diner",
        "Waiter_Market",
        "Waiter_PileOCrepe",
        "Waiter_PizzaWhirled",
        "Waiter_Restaurant",
        "Waiter_Spiffo",
        "Waiter_TachoDelPancho",
        "WaiterStripper" },
    Farm = {
        "Hunter",
        "Woodcut",
        "Jockey01",
        "Jockey02",
        "Jockey03",
        "Jockey06"
    },
    Forest = {
        "Hunter",
        "Woodcut",
        "Fisherman" },
    Nav = {
        "Fisherman"
    },
    TrailerPark = {
        "Thug",
        "Bandit"
    },
    Vegitation = {
        "Inmate",
        "InmateEscaped",
        "InmateKhaki"
    },
    Default = {
        "TutorialDad"
    }

}