--HTC_SPAWN_CONFIGS = {
--    "Jackie_Jaye",
--    "Joan",
--    "Kate",
--    "Kirsty_Kormick",
--    "Young",
--    "Bob",
--    "Dean",
--    "Duke",
--    "Frank_Hemingway",
--    "Ghillie",
--    "John",
--    "Judge_Matt_Hass",
--    "Mayor_West_point",
--    "McCoys",
--    "Rev_Peter_Watts",
--    "Sir_Twiggy",
--    "TutorialDad",

HTC_SPAWN_CONFIGS = {
    TownZone = {
        "Bathrobe",
        "Bedroom",
        "Priest",
        "PrivateMilitia",
        "HospitalPatient",
        "Fireman",
        "FiremanFullSuit",
        "FitnessInstructor",
        "Fossoil",
        "Gas2Go",
        "Hobbo",
        "HazardSuit",
        "BaseballFan_KY",
        "BaseballFan_Rangers",
        "BaseballFan_Z",
        "BaseballPlayer_KY",
        "BaseballPlayer_Rangers",
        "BaseballPlayer_Z",
        "ShellSuit_Black",
        "ShellSuit_Blue",
        "ShellSuit_Green",
        "ShellSuit_Pink",
        "ShellSuit_Teal",
        "Biker",
        "Cyclist",
        "Doctor",
        "DressLong",
        "DressNormal",
        "DressShort",
        "AmbulanceDriver",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "GigaMart_Employee",
        "Golfer",
        "Bowling",
        "BoxingBlue",
        "BoxingRed",
        "Chef",
        "Classy",
        "Cook_Generic",
        "Cook_IceCream",
        "Cook_Spiffos",
        "Mannequin1",
        "Mannequin2",
        "Nurse",
        "ThunderGas",
        "StripperPink",
        "Ski Spiffo",
        "StripperBlack",
        "SportsFan",
        "StreetSports",
        "OfficeWorkerSkirt",
        "Punk",
        "Rocker",
        "Tourist",
        "Santa",
        "SantaGreen",
        "Raider",
        "Party",
        "Postal",
        "Pharmacist",
        "ConstructionWorker",
        "Varsity",
        "Student",
        "Swimmer",
        "Teacher",
        "Trader",
        "Groom",
        "MallSecurity",
        "OfficeWorker",
        "PokerDealer",
        "MetalWorker",
        "Mechanic",
        "Jewelry",
        "Mechanic",
        "Police",
        "PoliceState",
        "PoliceRiot",
        "PrisonGuard",
        "Trader",
        "Waiter_TacoDelPancho",
        "Security",
        "ArmyServiceUniform",
        "Waiter_Classy",
        "Waiter_Diner",
        "Waiter_Market",
        "Waiter_PileOCrepe",
        "Waiter_PizzaWhirled",
        "Waiter_Restaurant",
        "Waiter_Spiffo",
        "Waiter_TachoDelPancho",
        "WaiterStripper",
        "Priest",
        "Veteran",
        "StreetSports",
        "StripperBlack",
        "StripperPink",
    },
    TrailerPark = {
        "Camper",
        "Priest",
        "PrivateMilitia",
        "Fireman",
        "FiremanFullSuit",
        "FitnessInstructor",
        "Fossoil",
        "Gas2Go",
        "Hobbo",
        "HazardSuit",
        "Raider",
        "Biker",
        "Cyclist",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "TinFoilHat",
        "Punk",
        "Rocker",
        "Redneck",
        "Postal",
        "Raider",
        "ConstructionWorker",
        "Student",
        "Varsity",
        "PoliceState",
        "Thug",
        "Bandit",
        "Survivalist",
        "Survivalist02",
        "Survivalist03",

        "Ranger",
    },
    Farm = {
        "Camper",
        "Priest",
        "PrivateMilitia",
        "HazardSuit",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "Farmer",
        "Redneck",
        "Postal",
        "ConstructionWorker",
        "Student",
        "MetalWorker",
        "PoliceState",
        "Mechanic",
        "Fisherman",
        "Hunter",
        "Woodcut",
        "Jockey01",
        "Jockey02",
        "Jockey03",
        "Jockey04",
        "Jockey05",
        "Jockey06",
        "Priest",
        "Ranger",
    },
    Vegitation = {
        "Camper",
        "PrivateMilitia",
        "HospitalPatient",
        "HazardSuit",
        "Raider",
        "ShellSuit_Black",
        "ShellSuit_Blue",
        "ShellSuit_Green",
        "ShellSuit_Pink",
        "ShellSuit_Teal",
        "Biker",
        "Cyclist",
        "AmbulanceDriver",
        "ArmyCamoDesert",
        "ArmyCamoGreen",
        "ArmyServiceUniform",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "Farmer",
        "Golfer",
        "Punk",
        "Rocker",
        "Redneck",
        "Postal",
        "ConstructionWorker",
        "PrisonGuard",
        "PoliceState",
        "Inmate",
        "InmateEscaped",
        "InmateKhaki",
        "Survivalist",
        "Survivalist02",
        "Survivalist03",
        "Fisherman",
        "Hunter",
        "Woodcut",
        "Jockey01",
        "Jockey02",
        "Jockey03",
        "Jockey04",
        "Jockey05",
        "Jockey06",

    },
    Forest = {
        "Camper",
        "PrivateMilitia",
        "Raider",
        "AmbulanceDriver",
        "ArmyCamoDesert",
        "ArmyCamoGreen",
        "ArmyServiceUniform",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "Golfer",
        "TinFoilHat",
        "Fisherman",
        "PrisonGuard",
        "PoliceState",
        "Inmate",
        "InmateEscaped",
        "InmateKhaki",
        "PoliceState",
        "Hunter",
        "Woodcut",
        "Fisherman",
        "Survivalist",
        "Survivalist02",
        "Survivalist03",
        "Ranger",
    },
    DeepForest = {
        "Camper",
        "Raider",
        "AmbulanceDriver",
        "ArmyCamoDesert",
        "ArmyCamoGreen",
        "ArmyServiceUniform",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "PrisonGuard",
        "PoliceState",
        "Inmate",
        "InmateEscaped",
        "InmateKhaki",
        "HockeyPsycho",
        "Hunter",
        "Woodcut",
        "PoliceState",
        "AirCrew",
        "ArmyCamoGreen",
        "ArmyServiceUniform",
        "Veteran",
        "Survivalist",
        "Survivalist02",
        "Survivalist03",
        "Ranger",
    },
    Nav = {
        "PrivateMilitia",
        "Raider",
        "Biker",
        "Cyclist",
        "Generic_Skirt",
        "Generic01",
        "Generic02",
        "Generic03",
        "Generic04",
        "Generic05",
        "PrisonGuard",
        "MetalWorker",
        "PoliceState",
        "Fisherman"
    },
    Default = {
        "TutorialMom",
        "TutorialDad"
    }

}